from __future__ import annotations
from pathlib import Path
import pandas as pd
try:
    from src import metrics
except ModuleNotFoundError:
    import metrics
ROOT=Path(__file__).resolve().parents[1]; OUTPUT=ROOT/'data'/'processed'/'consultant_gap_log.csv'
def gap(gid,area,metric,actual,expected,severity,evidence,action,owner,follow):
    return {'gap_id':gid,'area':area,'metric':metric,'actual_value':actual,'expected_value':expected,'severity':severity,'evidence':evidence,'probable_cause':'Hipótese provável: os dados sugerem fragilidade de regra, processo ou accountability operacional; precisa ser validado antes de confirmar causa raiz.','missing_evidence':'Regras reais do CRM, exceções aprovadas, notas comerciais, motivo de alteração, critérios de forecast e validação dos managers.','validation_questions':'O comportamento observado vem de regra de sistema, disciplina operacional, mix de carteira, exceção aprovada ou ausência de governança?','recommended_action':action,'owner':owner,'urgency':'immediate' if severity=='critical' else 'this_week' if severity=='high' else 'this_month','expected_impact':'Melhorar forecast, pipeline hygiene, produtividade comercial, governança e qualidade da decisão executiva.','follow_up_metric':follow,'status':'open'}
def add(rows,cond,*args):
    if cond: rows.append(gap(*args))
def find_gaps(tables=None):
    t=tables or metrics.load_all(); l=t['leads']; a=t['accounts']; c=t['contacts']; o=t['opportunities']; acts=t['activities']; audit=t['crm_audit_log']; tasks=t['remediation_tasks']; rows=[]
    score=metrics.crm_data_quality_score(t); fscore=metrics.forecast_reliability_score(o,acts); hscore=metrics.pipeline_hygiene_score(o,acts); rev=metrics.revenue_at_risk_from_data_quality(o); lm=metrics.lead_missing_source_rate(l); manual=metrics.manual_close_date_change_rate(audit)
    add(rows,score<82,'gap_low_crm_data_quality_score','crm_governance','crm_data_quality_score',round(score,1),'>= 82','critical',f'Os dados sugerem score geral de qualidade em {score:.1f}/100.','Criar war room de CRM hygiene com owners por objeto e foco em campos críticos.','Head de RevOps','crm_data_quality_score')
    add(rows,lm>.05,'gap_leads_without_source','lead_governance','lead_missing_source_rate',round(lm,3),'<= 0.05','high',f'A evidência disponível aponta para {lm:.1%} dos leads sem source.','Bloquear criação ou roteamento de lead sem source.','Marketing Ops','lead_missing_source_rate')
    add(rows,len(metrics.duplicate_leads(l))>0,'gap_duplicate_leads','deduplication','duplicate_leads',len(metrics.duplicate_leads(l)),'0','medium',f'Há indícios de {len(metrics.duplicate_leads(l))} leads duplicados por email.','Ativar dedupe por email antes do roteamento.','Sales Ops','duplicate_lead_rate')
    add(rows,len(metrics.duplicate_accounts(a))>0,'gap_duplicate_accounts','deduplication','duplicate_accounts',len(metrics.duplicate_accounts(a)),'0','high',f'Os dados sugerem {len(metrics.duplicate_accounts(a))} contas duplicadas por nome e domínio.','Consolidar contas duplicadas e criar matching por domínio.','CRM Manager','duplicate_account_rate')
    add(rows,len(metrics.contacts_without_account(c))>0,'gap_contacts_without_account','relationship_integrity','contacts_without_account',len(metrics.contacts_without_account(c)),'0','medium',f'Há {len(metrics.contacts_without_account(c))} contatos sem conta associada.','Associar contatos por domínio e exigir account_id.','CRM Admin','contacts_without_account')
    add(rows,len(metrics.accounts_without_owner(a))>0,'gap_accounts_without_owner','ownership','accounts_without_owner',len(metrics.accounts_without_owner(a)),'0','high',f'Há {len(metrics.accounts_without_owner(a))} contas sem owner.','Fazer backfill de owner e criar regra diária de atribuição.','Sales Ops Manager','accounts_without_owner')
    add(rows,len(metrics.opportunities_without_owner(o))>0,'gap_opportunities_without_owner','ownership','opportunities_without_owner',len(metrics.opportunities_without_owner(o)),'0','critical',f'Existem {len(metrics.opportunities_without_owner(o))} oportunidades sem AE owner.','Atribuir owner antes de qualquer forecast inclusion.','Head de Sales','opportunities_without_owner')
    add(rows,len(metrics.opportunities_without_close_date(o))>0,'gap_opportunities_without_close_date','forecast_governance','opportunities_without_close_date',len(metrics.opportunities_without_close_date(o)),'0','critical',f'Há {len(metrics.opportunities_without_close_date(o))} oportunidades sem close_date.','Bloquear forecast de oportunidades abertas sem close_date validada.','RevOps','opportunities_without_close_date')
    add(rows,len(metrics.opportunities_without_next_step(o))>0,'gap_opportunities_without_next_step','pipeline_hygiene','opportunities_without_next_step',len(metrics.opportunities_without_next_step(o)),'0','high',f'Há {len(metrics.opportunities_without_next_step(o))} oportunidades abertas sem next_step.','Exigir next_step datado em pipeline review.','Sales Managers','opportunities_without_next_step')
    add(rows,len(metrics.stale_opportunities(o))>0,'gap_stale_opportunities','pipeline_hygiene','stale_opportunities',len(metrics.stale_opportunities(o)),'0','high',f'Há {len(metrics.stale_opportunities(o))} oportunidades paradas há mais de 20 dias.','Criar limpeza semanal de oportunidades paradas.','Sales Managers','stale_opportunities')
    add(rows,len(metrics.advanced_stage_without_activity(o,acts))>0,'gap_advanced_stage_without_activity','pipeline_hygiene','advanced_stage_without_activity',len(metrics.advanced_stage_without_activity(o,acts)),'0','high',f'Há {len(metrics.advanced_stage_without_activity(o,acts))} oportunidades em estágio avançado sem atividade recente.','Revisar deals avançados sem atividade.','Sales Managers','advanced_stage_without_activity')
    add(rows,len(metrics.closed_won_without_amount(o))>0,'gap_closed_won_without_amount','revenue_integrity','closed_won_without_amount',len(metrics.closed_won_without_amount(o)),'0','critical',f'Há {len(metrics.closed_won_without_amount(o))} Closed Won sem amount válido.','Corrigir amount antes de report executivo.','Finance/FP&A','closed_won_without_amount')
    add(rows,len(metrics.closed_lost_without_loss_reason(o))>0,'gap_closed_lost_without_loss_reason','loss_governance','closed_lost_without_loss_reason',len(metrics.closed_lost_without_loss_reason(o)),'0','high',f'Há {len(metrics.closed_lost_without_loss_reason(o))} Closed Lost sem loss_reason.','Exigir loss_reason e revisar taxonomia de perdas.','Sales Ops','closed_lost_without_loss_reason')
    add(rows,len(metrics.opportunities_with_zero_amount(o))>0,'gap_zero_amount_opportunities','revenue_integrity','opportunities_with_zero_amount',len(metrics.opportunities_with_zero_amount(o)),'0','high',f'Existem {len(metrics.opportunities_with_zero_amount(o))} oportunidades com amount zerado.','Definir stage gate para amount.','RevOps','opportunities_with_zero_amount')
    add(rows,len(metrics.open_opportunities_with_past_close_date(o))>0,'gap_past_close_date_open_opps','close_date_hygiene','open_opportunities_with_past_close_date',len(metrics.open_opportunities_with_past_close_date(o)),'0','critical',f'Há {len(metrics.open_opportunities_with_past_close_date(o))} oportunidades abertas com close_date no passado.','Revisar oportunidades vencidas e exigir reason code.','Head de Sales','open_opportunities_with_past_close_date')
    add(rows,len(metrics.forecast_category_inconsistencies(o))>0,'gap_forecast_category_inconsistencies','forecast_governance','forecast_category_inconsistencies',len(metrics.forecast_category_inconsistencies(o)),'0','critical',f'Há {len(metrics.forecast_category_inconsistencies(o))} forecast categories inconsistentes com stage.','Criar matriz stage x forecast category.','RevOps','forecast_category_inconsistencies')
    add(rows,len(metrics.invalid_stage_probability_combinations(o))>0,'gap_stage_probability_incompatibility','forecast_governance','invalid_stage_probability_combinations',len(metrics.invalid_stage_probability_combinations(o)),'0','high',f'Há {len(metrics.invalid_stage_probability_combinations(o))} probabilidades incompatíveis com stage.','Padronizar probability por stage.','CRM Manager','invalid_stage_probability_combinations')
    add(rows,manual>.35,'gap_manual_close_date_changes','close_date_hygiene','manual_close_date_change_rate',round(manual,3),'<= 0.35','high',f'Alterações manuais de close_date representam {manual:.1%} dos eventos.','Exigir reason code para pushes.','Sales Ops','manual_close_date_change_rate')
    add(rows,len(metrics.overdue_remediation_tasks(tasks))>0,'gap_overdue_remediation_tasks','remediation_governance','overdue_remediation_tasks',len(metrics.overdue_remediation_tasks(tasks)),'0','high',f'Há {len(metrics.overdue_remediation_tasks(tasks))} tarefas de remediação atrasadas.','Criar SLA semanal de remediação.','RevOps Manager','remediation_completion_rate')
    add(rows,fscore<78,'gap_low_forecast_reliability','forecast_governance','forecast_reliability_score',round(fscore,1),'>= 78','critical',f'Forecast reliability score está em {fscore:.1f}/100.','Rodar forecast cleanup antes da próxima reunião executiva.','CRO e Head de RevOps','forecast_reliability_score')
    add(rows,hscore<78,'gap_low_pipeline_hygiene','pipeline_hygiene','pipeline_hygiene_score',round(hscore,1),'>= 78','high',f'Pipeline hygiene score está em {hscore:.1f}/100.','Revisar oportunidades sem next_step, paradas, vencidas ou sem owner.','Sales Managers','pipeline_hygiene_score')
    add(rows,rev>1000000,'gap_high_revenue_at_risk','revenue_risk','revenue_at_risk_from_data_quality',round(rev,2),'<= 1000000','critical',f'Pipeline associado a problemas de qualidade soma R$ {rev:,.0f}.','Priorizar correção por valor em risco.','CRO','revenue_at_risk_from_data_quality')
    return pd.DataFrame(rows)
def main():
    gaps=find_gaps(); OUTPUT.parent.mkdir(parents=True,exist_ok=True); gaps.to_csv(OUTPUT,index=False); print(f'Consultant gap log generated at {OUTPUT} with {len(gaps)} gaps')
if __name__=='__main__': main()
