from __future__ import annotations
from pathlib import Path
import sqlite3
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]; PROCESSED=ROOT/'data'/'processed'; DOCS=ROOT/'docs'; REPORTS=ROOT/'reports'; DB=ROOT/'data'/'database'/'customer_health_case.sqlite'

def generate_data():
    PROCESSED.mkdir(parents=True,exist_ok=True); DB.parent.mkdir(parents=True,exist_ok=True); DOCS.mkdir(exist_ok=True); REPORTS.mkdir(exist_ok=True)
    csms=pd.DataFrame([['csm_001','Ana Martins','Enterprise'],['csm_002','Bruno Rocha','Enterprise'],['csm_003','Carla Nunes','Mid Market'],['csm_004','Diego Lima','SMB']],columns=['csm_id','csm_name','primary_segment'])
    rows=[]
    for i in range(1,37):
        seg='Enterprise' if i<=12 else 'Mid Market' if i<=24 else 'SMB'; csm='csm_002' if i in [3,5,8,11,14,18] else ('csm_001' if seg=='Enterprise' else 'csm_003' if seg=='Mid Market' else 'csm_004')
        mrr=60000-i*900 if seg=='Enterprise' else 18000-i*250 if seg=='Mid Market' else 4500-i*45
        rows.append([f'cus_{i:03d}',f'Cliente SaaS {i:03d}',seg,csm,'active',max(float(mrr),800),'Enterprise' if seg=='Enterprise' else 'Scale' if seg=='Mid Market' else 'Starter','tier_1' if seg=='Enterprise' else 'tier_2' if seg=='Mid Market' else 'tier_3','outdated' if i in [3,5,8,11,14] else 'current','2025-01-01','2026-06-10'])
    customers=pd.DataFrame(rows,columns=['customer_id','customer_name','segment','csm_id','status','current_mrr','plan','strategic_tier','success_plan_status','start_date','last_csm_touch_date'])
    customers.loc[customers.customer_id.isin(['cus_027','cus_031','cus_034']),'status']='churned'
    subscriptions=customers.assign(subscription_id='sub_'+customers.customer_id,mrr=customers.current_mrr,contract_start_date=customers.start_date,renewal_date='2026-09-30',billing_cycle='annual')[['subscription_id','customer_id','plan','mrr','status','contract_start_date','renewal_date','billing_cycle']]
    risk={'cus_003','cus_005','cus_008','cus_011','cus_014','cus_018'}; expand={'cus_002','cus_007','cus_016','cus_022','cus_026'}
    usage=[]
    for _,c in customers.iterrows():
        for w in range(26):
            base=75 if c.segment=='Enterprise' else 60 if c.segment=='Mid Market' else 45
            score=base + (w*0.6 if c.customer_id in expand else 0) - ((w-14)*2.2 if c.customer_id in risk and w>14 else 0)
            score=max(5,min(98,score))
            usage.append([f'use_{c.customer_id}_{w}',c.customer_id,(pd.Timestamp('2026-01-01')+pd.Timedelta(days=w*7)).date().isoformat(),int(score/3),35,int(score*10),int(score*4),round(score,1)])
    product_usage=pd.DataFrame(usage,columns=['usage_id','customer_id','week_start_date','active_users','licensed_users','key_feature_events','login_count','adoption_score'])
    tickets=[]
    for _,c in customers.iterrows():
        n=6 if c.customer_id in risk else 1
        for j in range(n): tickets.append([f'tic_{c.customer_id}_{j}',c.customer_id,'2026-06-01','' if j%2==0 else '2026-06-20','critical' if c.customer_id in risk and j<3 else 'medium','open' if j%2==0 else 'closed','bug',12.0])
    support_tickets=pd.DataFrame(tickets,columns=['ticket_id','customer_id','created_date','closed_date','severity','status','category','first_response_hours'])
    nps_surveys=pd.DataFrame([[f'nps_{c.customer_id}',c.customer_id,'2026-06-15',3 if c.customer_id in risk else 10 if c.customer_id in expand else 8,'executive_sponsor','synthetic_theme'] for _,c in customers.iterrows()],columns=['survey_id','customer_id','survey_date','nps_score','respondent_role','comment_theme'])
    qbr_events=pd.DataFrame([[f'qbr_{c.customer_id}',c.customer_id,'2026-01-15' if c.customer_id in risk else '2026-05-20',True,False if c.customer_id in risk else True,False if c.customer_id in risk else True,55] for _,c in customers.iterrows() if not (c.segment=='SMB' and int(c.customer_id[-3:])%3==0)],columns=['qbr_id','customer_id','qbr_date','executive_sponsor_present','success_plan_updated','next_steps_recorded','qbr_quality_score'])
    revenue_movements=pd.DataFrame([['mov_001','cus_003','2026-06-01','churn',54000.0,'lost_value','synthetic'],['mov_002','cus_027','2026-06-02','churn',3300.0,'lost_logo','synthetic'],['mov_003','cus_031','2026-06-03','churn',3000.0,'lost_logo','synthetic'],['mov_004','cus_008','2026-06-04','contraction',9000.0,'downgrade','synthetic'],['mov_005','cus_014','2026-06-05','contraction',7000.0,'seat_reduction','synthetic'],['mov_006','cus_002','2026-06-06','expansion',36000.0,'new_module','synthetic'],['mov_007','cus_007','2026-06-07','expansion',26000.0,'seat_growth','synthetic'],['mov_008','cus_016','2026-06-08','expansion',22000.0,'new_workspace','synthetic'],['mov_009','cus_022','2026-06-09','expansion',15000.0,'usage_growth','synthetic']],columns=['movement_id','customer_id','movement_date','movement_type','mrr_amount','reason','source'])
    last=product_usage.sort_values('week_start_date').groupby('customer_id').tail(1)[['customer_id','adoption_score']]; crit=support_tickets[support_tickets.severity.eq('critical')].groupby('customer_id').size().rename('critical_tickets').reset_index(); q=qbr_events.groupby('customer_id',as_index=False).qbr_date.max()
    h=customers[['customer_id','success_plan_status']].merge(last,on='customer_id').merge(crit,on='customer_id',how='left').merge(nps_surveys[['customer_id','nps_score']],on='customer_id').merge(q,on='customer_id',how='left'); h.critical_tickets=h.critical_tickets.fillna(0); h['days_since_last_qbr']=(pd.Timestamp('2026-06-30')-pd.to_datetime(h.qbr_date,errors='coerce')).dt.days.fillna(999)
    h['health_score']=(h.adoption_score*.42+h.nps_score*4-h.critical_tickets*8-h.days_since_last_qbr.gt(120)*12).clip(0,100).round(1); h['health_date']='2026-06-30'; h['risk_level']=pd.cut(h.health_score,[-1,39.9,59.9,79.9,100],labels=['critical','high','medium','low'])
    health_scores=h[['customer_id','health_date','health_score','risk_level','adoption_score','critical_tickets','nps_score','days_since_last_qbr']]
    expansion_opportunities=pd.DataFrame([['exp_001','cus_002','2026-06-10','new_module',36000.0,'qualified',.55,'2026-07-10','csm_001'],['exp_002','cus_007','2026-06-11','seat_growth',26000.0,'qualified',.55,'','csm_001'],['exp_003','cus_016','2026-06-12','usage_growth',22000.0,'discovery',.30,'2026-07-15','csm_003'],['exp_004','cus_022','2026-06-13','new_workspace',15000.0,'identified',.15,'','csm_003']],columns=['opportunity_id','customer_id','created_date','expansion_type','estimated_expansion_mrr','stage','probability','next_step','owner'])
    churn_events=pd.DataFrame([['chr_001','cus_003','2026-06-01',54000.0,'not_validated',False],['chr_002','cus_027','2026-06-02',3300.0,'not_validated',True],['chr_003','cus_031','2026-06-03',3000.0,'not_validated',False]],columns=['churn_event_id','customer_id','churn_date','churn_mrr','churn_reason','save_playbook_used'])
    tables=locals(); keep=['customers','csms','subscriptions','product_usage','support_tickets','nps_surveys','qbr_events','revenue_movements','health_scores','expansion_opportunities','churn_events']
    with sqlite3.connect(DB) as conn:
        for k in keep: tables[k].to_csv(PROCESSED/f'{k}.csv',index=False); tables[k].to_sql(k,conn,if_exists='replace',index=False)

def build_gap_log():
    c=pd.read_csv(PROCESSED/'customers.csv'); s=pd.read_csv(PROCESSED/'subscriptions.csv'); h=pd.read_csv(PROCESSED/'health_scores.csv'); u=pd.read_csv(PROCESSED/'product_usage.csv'); t=pd.read_csv(PROCESSED/'support_tickets.csv'); q=pd.read_csv(PROCESSED/'qbr_events.csv'); r=pd.read_csv(PROCESSED/'revenue_movements.csv'); e=pd.read_csv(PROCESSED/'expansion_opportunities.csv')
    m=c.merge(h,on='customer_id').merge(s[['customer_id','mrr']],on='customer_id'); base=s.mrr.sum(); churn=r.loc[r.movement_type.eq('churn'),'mrr_amount'].sum(); contraction=r.loc[r.movement_type.eq('contraction'),'mrr_amount'].sum(); exp=r.loc[r.movement_type.eq('expansion'),'mrr_amount'].sum(); grr=(base-churn-contraction)/base; nrr=(base-churn-contraction+exp)/base
    rows=[]
    def add(gid,area,metric,actual,expected,severity,evidence,cause,missing,question,action,owner,urgency,impact,follow): rows.append(dict(gap_id=gid,area=area,metric=metric,actual_value=actual,expected_value=expected,severity=severity,evidence=evidence,probable_cause=cause,missing_evidence=missing,validation_questions=question,recommended_action=action,owner=owner,urgency=urgency,expected_impact=impact,follow_up_metric=follow,status='open'))
    at=m[m.health_score.lt(60)]; hv=at[at.mrr.ge(25000)]; by=at.groupby('csm_id',as_index=False).mrr.sum(); no_next=e[e.next_step.fillna('').eq('')]; crit=t[t.severity.eq('critical')]
    add('gap_high_mrr_at_risk','Revenue Risk','high_mrr_at_risk',round(hv.mrr.sum(),2),'0','critical',f'{len(hv)} contas de alto MRR estao em risco.','Ha indicios de exposicao material em contas estrategicas.','Risco de budget, renovacao, concorrencia e sentimento do sponsor.','Qual e o plano executivo por conta?','Abrir war room de retencao para top contas.','Head of CS','24-48h','Proteger GRR e reduzir churn MRR.','at_risk_mrr')
    add('gap_csm_portfolio_risk','CSM Portfolio','at_risk_mrr_by_csm',round(by.mrr.max(),2),'<= 25% da carteira','critical','Uma carteira de CSM concentra parcela elevada de MRR em risco.','Ha indicios de desequilibrio de carteira ou cobertura insuficiente.','Capacidade real e carga de QBR.','A concentracao e estrutural?','Rebalancear carteira e criar cadencia executiva.','CS Ops Manager','esta semana','Melhorar eficiencia de CS.','csm_portfolio_risk')
    add('gap_grr_nrr_masking','Revenue Retention','grr_nrr_gap',round(nrr-grr,4),'GRR >= 1 ou gap explicado','critical',f'GRR esta em {grr:.1%} enquanto NRR esta em {nrr:.1%}.','Expansion MRR positivo pode estar mascarando perda bruta.','Motivos reais de churn e cohorts.','A expansao veio das mesmas contas saudaveis?','Reportar GRR e NRR juntos.','RevOps','imediato','Evitar decisao otimista baseada apenas em NRR.','grr_nrr_gap')
    add('gap_health_low','Customer Health','health_score',round(m.health_score.mean(),1),'>= 60','high',f'{len(at)} contas aparecem com health score baixo.','Os dados sugerem deterioracao de uso, experiencia ou cobertura.','Motivo qualitativo e plano de sucesso.','Quais contas tem plano ativo?','Priorizar contas com menor health score.','CS Ops + CSMs','esta semana','Reduzir MRR em risco.','health_score')
    add('gap_critical_tickets','Support Signals','critical_ticket_rate',len(crit),'< 8 tickets','high','Tickets criticos aparecem concentrados em contas estrategicas.','Ha indicios de friccao operacional.','SLA e status de resolucao.','Quais tickets bloqueiam valor?','Criar fila prioritaria para tier 1.','Support + CS','24-72h','Proteger GRR.','critical_ticket_rate')
    add('gap_qbr_coverage','Governance','accounts_without_recent_qbr',6,'0','high','Contas estao sem QBR recente.','Os dados sugerem lacuna de governanca.','Notas de reuniao e plano atualizado.','Quais contas sem QBR tem renovacao proxima?','Executar sprint de QBR.','CS Ops + CSMs','14 dias','Aumentar visibilidade de risco.','days_since_last_qbr')
    add('gap_expansion_no_next_step','Expansion Governance','expansion_without_next_step',len(no_next),'0','medium','Oportunidades de expansao existem sem proximo passo.','Os dados sugerem vazamento de pipeline por falta de cadencia.','Sponsor, budget e valor validado.','Qual e a proxima reuniao?','Definir proximo passo datado.','CSM + Sales','14 dias','Aumentar conversao de expansao.','expansion_without_next_step')
    out=pd.DataFrame(rows); out.to_csv(PROCESSED/'consultant_gap_log.csv',index=False); return out,dict(base=base,grr=grr,nrr=nrr,at_risk_mrr=at.mrr.sum(),expansion=e.estimated_expansion_mrr.sum())

def write_docs(g,sm):
    top='\n'.join(f'- {x.severity.upper()} | {x.area}: {x.evidence}' for x in g.itertuples()); crit=int(g.severity.eq('critical').sum()); high=int(g.severity.eq('high').sum())
    (DOCS/'ai_consultant_analysis.md').write_text(f'# AI Consultant Analysis\n\n## Veredito executivo\nA analise rule-based indica {crit} gaps criticos e {high} gaps altos. Os dados sugerem que expansao positiva pode mascarar perda bruta.\n\n## Leitura da operacao\nO problema parece concentrado em retencao bruta, cobertura de QBR, priorizacao de CSM, tickets criticos e governanca de playbooks.\n\n## Principais gaps identificados\n{top}\n\n## Hipoteses provaveis\nOs dados sugerem friccao de adocao, concentracao de risco e oportunidades sem cadencia. Precisa ser validado.\n\n## Evidencias observadas\nMRR em risco: {sm["at_risk_mrr"]:.2f}. GRR: {sm["grr"]:.1%}. NRR: {sm["nrr"]:.1%}.\n\n## Evidencias ausentes\n- Motivo real de churn.\n- Feedback qualitativo do cliente.\n- Notas de QBR.\n- Maturidade do onboarding.\n- Tickets resolvidos vs pendentes.\n- Uso por funcionalidade critica.\n- Adocao por persona.\n- Sentimento do sponsor.\n- Risco de budget.\n- Concorrencia.\n- Proximos passos registrados pelo CSM.\n- Plano de sucesso do cliente.\n\n## Perguntas para validacao\n- Head de CS: quais contas tem owner e data?\n- CS Ops: health score esta calibrado?\n- RevOps: GRR e NRR estao juntos?\n- Product: queda de uso afeta funcionalidade critica?\n- Support: tickets criticos tem SLA?\n\n## Recomendacoes priorizadas\n### Fazer agora\n- War room para alto MRR em risco.\n- Reportar GRR e NRR juntos.\n### Fazer depois\n- Rebalancear carteiras.\n- Criar playbook de queda de uso.\n### Monitorar\n- NPS por MRR, tickets criticos, adoption score e QBR.\n\n## Riscos de decisao\nDecidir apenas por NRR pode esconder churn e contraction.\n\n## Conclusao executiva\nA IA e rule-based e gera hipoteses para decisao executiva.\n',encoding='utf-8')
    (DOCS/'executive_analysis.md').write_text(f'# Analise Executiva\n\n## Veredito executivo\nA base nao deve ser lida como plenamente saudavel. NRR esta em {sm["nrr"]:.1%}, mas GRR esta em {sm["grr"]:.1%}.\n\n## Resumo de metricas\n- MRR total: R$ {sm["base"]:,.2f}\n- MRR em risco: R$ {sm["at_risk_mrr"]:,.2f}\n- Pipeline de expansao: R$ {sm["expansion"]:,.2f}\n- Gaps criticos: {crit}\n- Gaps altos: {high}\n\n## Diagnostico do periodo\nRisco aparece quando MRR alto, queda de uso, NPS detrator, tickets criticos e QBR vencido se combinam.\n\n## Principais achados\n{top}\n\n## Riscos\nNRR positivo pode mascarar GRR fraco.\n\n## Recomendacoes priorizadas\n1. Proteger contas de alto MRR em risco.\n2. Separar GRR e NRR.\n3. Rebalancear carteira.\n4. Executar sprint de QBR.\n5. Registrar proximo passo em expansao.\n\n## Limitacoes\nDados sinteticos e regras heuristicas.\n\n## Conclusao executiva\nCustomer Health deve ser sistema de decisao, nao painel descritivo.\n',encoding='utf-8')
    pd.DataFrame([sm]).to_csv(REPORTS/'executive_summary.csv',index=False)

def dq():
    expected=['customers','csms','subscriptions','product_usage','support_tickets','nps_surveys','qbr_events','revenue_movements','health_scores','expansion_opportunities','churn_events']; rows=[]
    for n in expected:
        p=PROCESSED/f'{n}.csv'; df=pd.read_csv(p) if p.exists() else pd.DataFrame(); rows.append(dict(check_name='file_exists',table=n,status='pass' if p.exists() else 'fail',details='expected file',row_count=len(df)))
    pd.DataFrame(rows).to_csv(PROCESSED/'data_quality_report.csv',index=False)

def main(): generate_data(); g,sm=build_gap_log(); write_docs(g,sm); dq(); print(f'customer health pipeline generated {len(g)} gaps')
if __name__=='__main__': main()
